---

# mssql Credential
mssql_user: 
mssql_password: 
mssql_connectionURL: 


#common vars
bin_dir: /usr/bin
destination_folder: /apps/
profile_path: /etc/profile.d
executables_loc: ~/<data location>/executables/autaeminstall.sh

#task - checkavail 
apps_loc: /apps

#task - java
#java_loc: ~/<data location>/softwares/jdk-8u181-linux-x64.tar.gz
java_loc: ~/<data location>/softwares/jdk-8u111-linux-x64.tar.gz
owner_user: root
group_user: root
javadest_folder: /apps/java/
java_deploymentDir: /etc/.java/deployment/
java_bin: /apps/java/java/bin

# task - Apache
apache_loc: ~/<data location>/softwares/apache_softwares.tar
ap_owner_user: root
ap_group_user: root

# task - aem
aem_loc: ~/<data location>/softwares/aemforms_server_6_3_0_jboss_all_unix.tar.gz
aem_dest: /apps/aemforms_server_6_3_0_jboss_all_unix/
adobe_loc: /apps/adobe/adobe_experience_manager_Forms/

jboss_dlink: http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip
jboss_zip: jboss-as-7.1.1.Final.zip
jboss_Final: jboss-as-7.1.1.Final

jboss_loggingjar_loc: /apps/adobe/adobe_experience_manager_Forms/jboss-as-7.1.1.Final/modules/org/jboss/logging/main/jboss-logging-3.1.0.GA.jar

jar_command: java -cp /apps/adobe/adobe_experience_manager_Forms/jboss-as-7.1.1.Final/modules/org/picketbox/main/picketbox-4.0.7.Final.jar:/apps/adobe/adobe_experience_manager_Forms/jboss-as-7.1.1.Final/modules/org/picketbox/main/picketbox-commons-1.0.0.final.jar:/apps/adobe/adobe_experience_manager_Forms/jboss-as-7.1.1.Final/modules/org/picketbox/mainpicketbox-infinispan-4.0.7.Final.jar:/apps/adobe/adobe_experience_manager_Forms/jboss-as-7.1.1.Final/modules/org/jboss/logging/main/jboss-logging-3.1.0.GA.jar org.picketbox.datasource.security.SecureIdentityLoginModule

# task- Jboss
#jboss_dlink: http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.tar.gz
jboss_binloc: /apps/adobe/adobe_experience_manager_Forms/jboss/bin/
jbosstemplate_loc: ~/<data location>/roles/pro_jboss/templates/jbossas7
confBin_loc: /apps/adobe/adobe_experience_manager_Forms/configurationManager/bin/
clioptions_templateLoc: ~/<data location>/roles/pro_jboss/templates/clioptions.txt

mssql_conn_regexp: ^(.*)<connection-url>jdbc:sqlserver://localhost:1433(.*)$
mssql_conn_replace: <connection-url>jdbc:sqlserver://<mysqlhost>:1433;DatabaseName=<DB name>;encrypt=true;trustServerCertificate=true;hostNameInCertificate=<hostname certificate></connection-url>


# task- Standalonefile Update
jboss_standalone1: JAVA_OPTS="-Xms1024m -Xmx4096m -XX:MaxMetaspaceSize=1024m -D64 -XX:+HeapDumpOnOutOfMemoryError -XX:+UseCompressedOops"
jboss_standalone2: JAVA_OPTS="$JAVA_OPTS -DentityExpansionLimit=10000 -Djava:io.tmpdir=/apps/adobe/adobe_experience_manager_Forms/JavaTemp"
jboss_standalone3: ^(.*)JAVA_OPTS="$JAVA_OPTS -Djboss.server.default.config=standalone.xml -Dlc.um.csrffilter.disabled=true"(.*)$ 
jboss_standalone4: JAVA_OPTS="$JAVA_OPTS -Djboss.server.default.config=standalone.xml"
jboss_standalone5: ^(.*)JAVA_OPTS="$JAVA_OPTS -Dadobeidp.serverName=server1 -Dfile.encoding=utf8 -Djava.net.preferIPv4Stack=true -Dcom.adobe.livecycle.crx.integration.url=http://localhost:8080"(.*)$
jboss_standalone6: JAVA_OPTS="$JAVA_OPTS -Dadobeidp.serverName=server1 -Dfile.encoding=utf8 -Djava.net.preferIPv4Stack=true -Dcom.adobe.livecycle.crx.integration.url=http://localhost:80"
jboss_ip: 192.167.1.7

#lc_msql file variables
lcmssqltemplate_loc: ~/<data location>/roles/pro_jboss/templates/lc_mssql.xml
standaloneconf_loc: /apps/adobe/adobe_experience_manager_Forms/jboss/standalone/configuration/

lc_mssql1: <socket-binding name="http" interface="any" port="80"/>
lc_mssql2: <socket-binding name="https" interface="any" port="443"/>

 
# task- jbossas7 file
ConsoleLog: /apps/adobe/adobe_experience_manager_Forms/jboss/log/console.log
HostControllerLog: /apps/adobe/adobe_experience_manager_Forms/jboss/standalone/log/host-controller.log
ProcessControllerLog: /apps/adobe/adobe_experience_manager_Forms/jboss/standalone/log/process-controller.log
ServerLog: /apps/adobe/adobe_experience_manager_Forms/jboss/standalone/log/server.log
CrxErrorLog: /apps/adobe/adobe_experience_manager_Forms/crx-repository/logs/error.log

#task - openssl
dispatcher_loc: ~/<data location>/softwares/dispatcher-apache2.4-4.2.3.so
dispatcher_src_file: ~/<data location>/softwares/dispatcher.any
apache_folder: /apps/apache/2.4.6/
apache_conf_file: /apps/apache/2.4.6/conf/httpd.conf
dispatcher_file: /apps/apache/2.4.6/conf/dispatcher.any
apache_conf_folder: /apps/apache/2.4.6/conf
apache_sslconf_file: /apps/apache/2.4.6/conf/extra/httpd-ssl.conf


# task - post_installation

base_url: localhost:8080
mysql_jdbc_jar: mssql-jdbc-6.2.2.jre8.jar
aem63_component_zip: aem63-core-components.zip
acs_aem_zip: acs-aem-commons-content-3.11.0.zip
home_loc: /home/devadmin/
connector_http: <connector name="http" protocol="HTTP/1.1" scheme="http" socket-binding="http"/>
connector_https: <connector name="https" protocol="HTTP/1.1" scheme="https" socket-binding="https" secure="true">
ssl_certificate_block: <ssl certificate-key-file="/apps/adobe/adobe_experience_manager_Forms/jboss/standalone/configuration/ansible.keystore" key-alias="ansible" password="changeit" />
aem63_component_zip_loc: ~/<data location>/softwares/acs-aem-commons-content-3.11.0.zip
acs_aem_zip_loc: ~/<data location>/softwares/acs-aem-commons-content-3.11.0.zip
