---
- name: Comment out pipeline archive in fstab
  replace:
    dest: /bin/pod2man
    regexp: '\$parser->parse_from_file'
    replace: '#$parser->parse_from_file'

- name: Extracting openssl
  unarchive: "src={{ destination_folder }}apache_softwares/openssl-1.0.1e.tar.gz dest={{ destination_folder }}apache_softwares/ copy=no"

- name: Install openssl
  command: "{{ item }} chdir={{ destination_folder }}apache_softwares/openssl-1.0.1e"
  with_items:
  - ./config --prefix=/apps/ssl/1.0.1e --openssldir=/apps/openssl/1.0.1e
  - /usr/bin/make
  - /usr/bin/make install

-
  command: "{{ item }} chdir={{ bin_dir }}"
  ignore_errors: true
  name: "Create link"
  with_items:
    - "ln -s {{ destination_folder }}ssl/1.0.1e/bin/openssl openssl"
