---
- hosts: AemAut
  become: true
  tasks:
  
  - name: "Copy LC_cert.cer on Author"
    copy:
      src: /home/devadmin/community-force_automation/ansible/softwares/LC_cert.cer
      dest: "{{ home_loc }}" 

  - name: "Import Keytool"
    command: "{{ item }} chdir={{ home_loc }}"
    with_items:
      - "/apps/java/bin/keytool -import -alias {{ alias_name }} -file LC_cert.cer -keystore /apps/java/jre/lib/security/cacerts"

  - name: "Post installation Commands"
    command: "{{ item }} chdir={{ home_loc }}"
    with_items:
      - 'curl -u admin:admin -F "jcr:primaryType=sling:OsgiConfig" -F "alias=/crx/server" -F "dav.create-absolute-uri=true" -F "dav.create-absolute-uri@TypeHint=Boolean" http://localhost:4502/system/config/org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet'
