---
- 
  name: "Transfer the Jar"
  copy: "src={{ aem_loc }}  dest={{ destination_folder }} mode=755"

- name: "Transfer the lic file"
  copy: "src={{ lic_loc }} dest={{ destination_folder }} mode=755"

-  
  name: Execute the script
  script: "{{ executables_loc }}"
  args:
    executable: /usr/bin/bash

- include_tasks: confupdate.yml
- include_tasks: service.yml
