---
- name: "Populate /etc/.java dir"
  file: "path={{ java_deploymentDir }} state=directory"

- name: Create deployment.properties
  file:
    path: "{{ java_deploymentDir }}deployment.properties"
    state: touch

- 
  blockinfile: 
    content: |
       "deployment.security.level=VERY_HIGH"
       "deployment.security.level.locked"
       "deployment.webjava.enabled=true"
       "deployment.webjava.enabled.locked"
       "deployment.security.askgrantdialog.notinca=false"
       "deployment.security.askgrantdialog.notinca.locked"
       "deployment.security.askgrantdialog.show=false"
       "deployment.security.askgrantdialog.show.locked"
       "deployment.security.validation.ocsp=true"
       "deployment.security.validation.ocsp.locked"
       "deployment.security.blacklist.check=true"
       "deployment.security.blacklist.check.locked"
       "deployment.user.security.exception.sites={{ java_deploymentDir }}exception.sites"
       "deployment.security.revocation.check=ALL_CERTIFICATES"
       "deployment.security.revocation.check.locked"
       "deployment.security.validation.crl=true"
       "deployment.security.validation.crl.locked"
       "deployment.insecure.jres=PROMPT"
       "deployment.insecure.jres.locked"
    path: "{{ java_deploymentDir }}deployment.properties" 
  name: ".java deployment properties data"

